### ISSUE TITLE
created 3 radowsgw with buckets: rookify seems not to find them

### ISSUE THREAD

**Issue by boekhorstb1** [SovereignCloudStack/rookify#105]
Hi!

tested around in with cephadm a bit more. 

Got following rgw pools:

```root@master:
ceph osd pool ls | grep rgw
.rgw.root
localtesting-zone.rgw.log
localtesting-zone.rgw.control
localtesting-zone.rgw.meta
default.rgw.meta
default.rgw.log
default.rgw.control
``` 

I got the following error from rookify:

```
Traceback (most recent call last):
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/bin/rookify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lerch/dev/cephadm_testing_setup/rookify/src/rookify/__main__.py", line 80, in main
    machine.execute(dry_run_mode=args.dry_run_mode)
  File "/home/lerch/dev/cephadm_testing_setup/rookify/src/rookify/modules/machine.py", line 44, in execute
    self._execute(file)
  File "/home/lerch/dev/cephadm_testing_setup/rookify/src/rookify/modules/machine.py", line 55, in _execute
    self.next_state()
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/lib64/python3.12/site-packages/transitions/core.py", line 402, in trigger
    return self.machine._process(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/lib64/python3.12/site-packages/transitions/core.py", line 1211, in _process
    return trigger()
           ^^^^^^^^^
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/lib64/python3.12/site-packages/transitions/core.py", line 416, in _trigger
    self._process(event_data)
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/lib64/python3.12/site-packages/transitions/core.py", line 439, in _process
    if trans.execute(event_data):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/lib64/python3.12/site-packages/transitions/core.py", line 277, in execute
    self._change_state(event_data)
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/lib64/python3.12/site-packages/transitions/core.py", line 287, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/lib64/python3.12/site-packages/transitions/extensions/states.py", line 103, in enter
    return super(Timeout, self).enter(event_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/lib64/python3.12/site-packages/transitions/core.py", line 129, in enter
    event_data.machine.callbacks(self.on_enter, event_data)
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/lib64/python3.12/site-packages/transitions/core.py", line 1146, in callbacks
    self.callback(func, event_data)
  File "/home/lerch/dev/cephadm_testing_setup/rookify/.venv/lib64/python3.12/site-packages/transitions/core.py", line 1167, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/home/lerch/dev/cephadm_testing_setup/rookify/src/rookify/modules/migrate_rgw_pools/main.py", line 60, in preflight
    raise ModuleException(
rookify.modules.exception.ModuleException: Failed to identify required pools for RGW zone 'localtesting-zone'
```

Now I created the rgws manually, so might have made mistake but I think rgw module does not find them somehow.

**Comment by boekhorstb1** [comment]
now sure why it did now work, but after I added a user with access to the buckets and also let the user add some file to a bucket at least `rookify -d` worked.
