### ISSUE TITLE
rookify dry run error 

### ISSUE THREAD

**Issue by boekhorstb1** [SovereignCloudStack/rookify#76]
Config is copied over from `config.example.yaml`. Changed only this section:

```yaml
# config.yaml
migration_modules:
- create_rook_cluster
- migrate_osds
- migrate_osd_pools
- migrate_mds
- migrate_mds_pools
- migrate_rgws
- migrate_rgw_pools
```
Then I ran this:

```bash
 .venv/bin/rookify --dry-run                                                                                                                   
2024-09-04 08:31.20 [info     ] Execution started with machine pickle file
2024-09-04 08:31.21 [info     ] AnalyzeCephHandler ran successfully.
2024-09-04 08:31.22 [info     ] Validated Ceph to expect cephx auth
Traceback (most recent call last):
  File "/home/user/dev/scs/rookify-update-makefile/.venv/bin/rookify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/dev/scs/rookify-update-makefile/src/rookify/__main__.py", line 33, in main
    machine.execute(args.dry_run_mode)
  File "/home/user/dev/scs/rookify-update-makefile/src/rookify/modules/machine.py", line 50, in execute
    self._execute(file)
  File "/home/user/dev/scs/rookify-update-makefile/src/rookify/modules/machine.py", line 64, in _execute
    self.next_state()
  File "/home/user/.local/lib/python3.12/site-packages/transitions/core.py", line 402, in trigger
    return self.machine._process(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/transitions/core.py", line 1211, in _process
    return trigger()
           ^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/transitions/core.py", line 416, in _trigger
    self._process(event_data)
  File "/home/user/.local/lib/python3.12/site-packages/transitions/core.py", line 439, in _process
    if trans.execute(event_data):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/transitions/core.py", line 277, in execute
    self._change_state(event_data)
  File "/home/user/.local/lib/python3.12/site-packages/transitions/core.py", line 287, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/home/user/.local/lib/python3.12/site-packages/transitions/extensions/states.py", line 103, in enter
    return super(Timeout, self).enter(event_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/transitions/core.py", line 129, in enter
    event_data.machine.callbacks(self.on_enter, event_data)
  File "/home/user/.local/lib/python3.12/site-packages/transitions/core.py", line 1146, in callbacks
    self.callback(func, event_data)
  File "/home/user/.local/lib/python3.12/site-packages/transitions/core.py", line 1167, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/home/user/dev/scs/rookify-update-makefile/src/rookify/modules/create_rook_cluster/main.py", line 18, in preflight
    if self.machine.get_execution_state_data(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/scs/rookify-update-makefile/src/rookify/modules/machine.py", line 100, in get_execution_state_data
    return getattr(self.get_execution_state(name), tag, default_value)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/scs/rookify-update-makefile/src/rookify/modules/machine.py", line 95, in get_execution_state
    return self.get_state(self.__class__.STATE_NAME_EXECUTION_PREFIX + name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/transitions/core.py", line 748, in get_state
    raise ValueError("State '%s' is not a registered state." % state)
ValueError: State 'ExecutionCreateRookClusterHandler' is not a registered state.
```

**Comment by NotTheEvilOne** [comment]
Please verify that the latest PR fixes the issues you have seen.

**Comment by boekhorstb1** [comment]
ok confirmed
